
import javax.swing.JOptionPane;
import masterDetail.parametros;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class interfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form interfazPrincipal
     */
    public interfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        logoCentroSur = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuFactura = new javax.swing.JMenu();
        menuFacturaServ = new javax.swing.JMenu();
        item_ConsultaFacServ = new javax.swing.JMenuItem();
        item_GenerarFacturaServ = new javax.swing.JMenuItem();
        itemMantenimientoFactServ = new javax.swing.JMenuItem();
        menuFacturaInst = new javax.swing.JMenu();
        item_ConsultaFacInst = new javax.swing.JMenuItem();
        item_GenerarFacturaInst = new javax.swing.JMenuItem();
        itemMantenimientoFactInst = new javax.swing.JMenuItem();
        menuLectura = new javax.swing.JMenu();
        menuConsultaLectura = new javax.swing.JMenu();
        itemCRUDLectura = new javax.swing.JMenuItem();
        menuParametro = new javax.swing.JMenu();
        menuConsultaParametro = new javax.swing.JMenu();
        itemCRUDParametro = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenu();
        itemAyudaAcercaDe = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        logoCentroSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoCentroSur.JPG"))); // NOI18N

        menuFactura.setText("Facturas");

        menuFacturaServ.setText("Servicio");

        item_ConsultaFacServ.setText("Consultas");
        item_ConsultaFacServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ConsultaFacServActionPerformed(evt);
            }
        });
        menuFacturaServ.add(item_ConsultaFacServ);

        item_GenerarFacturaServ.setText("Generar Factura");
        item_GenerarFacturaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_GenerarFacturaServActionPerformed(evt);
            }
        });
        menuFacturaServ.add(item_GenerarFacturaServ);

        itemMantenimientoFactServ.setText("Mantenimiento");
        menuFacturaServ.add(itemMantenimientoFactServ);

        menuFactura.add(menuFacturaServ);

        menuFacturaInst.setText("Instalacion");

        item_ConsultaFacInst.setText("Consultas");
        menuFacturaInst.add(item_ConsultaFacInst);

        item_GenerarFacturaInst.setText("Generar Factura");
        menuFacturaInst.add(item_GenerarFacturaInst);

        itemMantenimientoFactInst.setText("Mantenimiento");
        menuFacturaInst.add(itemMantenimientoFactInst);

        menuFactura.add(menuFacturaInst);

        barraMenu.add(menuFactura);

        menuLectura.setText("Lecturas");

        menuConsultaLectura.setText("Consultas");
        menuLectura.add(menuConsultaLectura);

        itemCRUDLectura.setText("CRUD");
        itemCRUDLectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCRUDLecturaActionPerformed(evt);
            }
        });
        menuLectura.add(itemCRUDLectura);

        barraMenu.add(menuLectura);

        menuParametro.setText("Parametros");

        menuConsultaParametro.setText("Consultas");
        menuParametro.add(menuConsultaParametro);

        itemCRUDParametro.setText("CRUD");
        itemCRUDParametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCRUDParametroActionPerformed(evt);
            }
        });
        menuParametro.add(itemCRUDParametro);

        barraMenu.add(menuParametro);

        jMenu1.setText("Otros");

        jMenuItem2.setText("Medidor CRUD");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Calles CRUD");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Predio CRUD");
        jMenu1.add(jMenuItem4);

        jMenuItem6.setText("Rubro CRUD");
        jMenu1.add(jMenuItem6);

        jMenuItem5.setText("Propietario CRUD");
        jMenu1.add(jMenuItem5);

        barraMenu.add(jMenu1);

        menuAcercaDe.setText("Acerca de");

        itemAyudaAcercaDe.setText("Ayuda");
        itemAyudaAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAyudaAcercaDeActionPerformed(evt);
            }
        });
        menuAcercaDe.add(itemAyudaAcercaDe);

        barraMenu.add(menuAcercaDe);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoCentroSur)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoCentroSur)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_GenerarFacturaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_GenerarFacturaServActionPerformed
        generarFactura FacServ = new generarFactura(this,true);
        FacServ.setVisible(true);
    }//GEN-LAST:event_item_GenerarFacturaServActionPerformed

    private void item_ConsultaFacServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ConsultaFacServActionPerformed
        interfazConsultaFactServ consulta = new interfazConsultaFactServ(this,true);
        consulta.setVisible(true);
    }//GEN-LAST:event_item_ConsultaFacServActionPerformed

    private void itemCRUDParametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCRUDParametroActionPerformed
        parametros.main(new String[0]);
    }//GEN-LAST:event_itemCRUDParametroActionPerformed

    private void itemAyudaAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAyudaAcercaDeActionPerformed
        JOptionPane.showMessageDialog(null,"David Tapia, Andres C. 2016\nSistema de Facturacion Electrica\nB.D. 5to A");
    }//GEN-LAST:event_itemAyudaAcercaDeActionPerformed

    private void itemCRUDLecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCRUDLecturaActionPerformed
       
    }//GEN-LAST:event_itemCRUDLecturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemAyudaAcercaDe;
    private javax.swing.JMenuItem itemCRUDLectura;
    private javax.swing.JMenuItem itemCRUDParametro;
    private javax.swing.JMenuItem itemMantenimientoFactInst;
    private javax.swing.JMenuItem itemMantenimientoFactServ;
    private javax.swing.JMenuItem item_ConsultaFacInst;
    private javax.swing.JMenuItem item_ConsultaFacServ;
    private javax.swing.JMenuItem item_GenerarFacturaInst;
    private javax.swing.JMenuItem item_GenerarFacturaServ;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel logoCentroSur;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuConsultaLectura;
    private javax.swing.JMenu menuConsultaParametro;
    private javax.swing.JMenu menuFactura;
    private javax.swing.JMenu menuFacturaInst;
    private javax.swing.JMenu menuFacturaServ;
    private javax.swing.JMenu menuLectura;
    private javax.swing.JMenu menuParametro;
    // End of variables declaration//GEN-END:variables
}
