
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class interfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form interfazPrincipal
     */
    public interfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        logoCentroSur = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuFactura = new javax.swing.JMenu();
        menuFacturaServ = new javax.swing.JMenu();
        menuConsFacturaServ = new javax.swing.JMenu();
        item_ConsultaFacServCedula = new javax.swing.JMenuItem();
        item_ConsultaFacServNumFac = new javax.swing.JMenuItem();
        item_ConsultaFacServNumMed = new javax.swing.JMenuItem();
        item_GenerarFacturaServ = new javax.swing.JMenuItem();
        itemMantenimientoFactServ = new javax.swing.JMenuItem();
        menuFacturaInst = new javax.swing.JMenu();
        menuConsFacturaIns = new javax.swing.JMenu();
        item_ConsultaFacInstCedula = new javax.swing.JMenuItem();
        item_ConsultaFacInstNumFac = new javax.swing.JMenuItem();
        item_GenerarFacturaInst = new javax.swing.JMenuItem();
        itemMantenimientoFactInst = new javax.swing.JMenuItem();
        menuLectura = new javax.swing.JMenu();
        menuConsultaLectura = new javax.swing.JMenu();
        itemCRUDLectura = new javax.swing.JMenuItem();
        menuParametro = new javax.swing.JMenu();
        menuConsultaParametro = new javax.swing.JMenu();
        itemCRUDParametro = new javax.swing.JMenuItem();
        menuAcercaDe = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        logoCentroSur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoCentroSur.JPG"))); // NOI18N

        menuFactura.setText("Facturas");

        menuFacturaServ.setText("Servicio");

        menuConsFacturaServ.setText("Consultas");

        item_ConsultaFacServCedula.setText("Por cedula");
        menuConsFacturaServ.add(item_ConsultaFacServCedula);

        item_ConsultaFacServNumFac.setText("Por numero de factura");
        menuConsFacturaServ.add(item_ConsultaFacServNumFac);

        item_ConsultaFacServNumMed.setText("Por numero de medidor");
        menuConsFacturaServ.add(item_ConsultaFacServNumMed);

        menuFacturaServ.add(menuConsFacturaServ);

        item_GenerarFacturaServ.setText("Generar Factura");
        item_GenerarFacturaServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_GenerarFacturaServActionPerformed(evt);
            }
        });
        menuFacturaServ.add(item_GenerarFacturaServ);

        itemMantenimientoFactServ.setText("Mantenimiento");
        menuFacturaServ.add(itemMantenimientoFactServ);

        menuFactura.add(menuFacturaServ);

        menuFacturaInst.setText("Instalacion");

        menuConsFacturaIns.setText("Consultas");

        item_ConsultaFacInstCedula.setText("Por cedula");
        menuConsFacturaIns.add(item_ConsultaFacInstCedula);

        item_ConsultaFacInstNumFac.setText("Por numero de factura");
        item_ConsultaFacInstNumFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_ConsultaFacInstNumFacActionPerformed(evt);
            }
        });
        menuConsFacturaIns.add(item_ConsultaFacInstNumFac);

        menuFacturaInst.add(menuConsFacturaIns);

        item_GenerarFacturaInst.setText("Generar Factura");
        menuFacturaInst.add(item_GenerarFacturaInst);

        itemMantenimientoFactInst.setText("Mantenimiento");
        menuFacturaInst.add(itemMantenimientoFactInst);

        menuFactura.add(menuFacturaInst);

        barraMenu.add(menuFactura);

        menuLectura.setText("Lecturas");

        menuConsultaLectura.setText("Consultas");
        menuLectura.add(menuConsultaLectura);

        itemCRUDLectura.setText("CRUD");
        menuLectura.add(itemCRUDLectura);

        barraMenu.add(menuLectura);

        menuParametro.setText("Parametros");

        menuConsultaParametro.setText("Consultas");
        menuParametro.add(menuConsultaParametro);

        itemCRUDParametro.setText("CRUD");
        menuParametro.add(itemCRUDParametro);

        barraMenu.add(menuParametro);

        menuAcercaDe.setText("Acerca de");
        barraMenu.add(menuAcercaDe);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoCentroSur)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoCentroSur)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void item_GenerarFacturaServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_GenerarFacturaServActionPerformed
        JOptionPane.showMessageDialog(null,"Hola que tal!");
    }//GEN-LAST:event_item_GenerarFacturaServActionPerformed

    private void item_ConsultaFacInstNumFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_ConsultaFacInstNumFacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_ConsultaFacInstNumFacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem itemCRUDLectura;
    private javax.swing.JMenuItem itemCRUDParametro;
    private javax.swing.JMenuItem itemMantenimientoFactInst;
    private javax.swing.JMenuItem itemMantenimientoFactServ;
    private javax.swing.JMenuItem item_ConsultaFacInstCedula;
    private javax.swing.JMenuItem item_ConsultaFacInstNumFac;
    private javax.swing.JMenuItem item_ConsultaFacServCedula;
    private javax.swing.JMenuItem item_ConsultaFacServNumFac;
    private javax.swing.JMenuItem item_ConsultaFacServNumMed;
    private javax.swing.JMenuItem item_GenerarFacturaInst;
    private javax.swing.JMenuItem item_GenerarFacturaServ;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel logoCentroSur;
    private javax.swing.JMenu menuAcercaDe;
    private javax.swing.JMenu menuConsFacturaIns;
    private javax.swing.JMenu menuConsFacturaServ;
    private javax.swing.JMenu menuConsultaLectura;
    private javax.swing.JMenu menuConsultaParametro;
    private javax.swing.JMenu menuFactura;
    private javax.swing.JMenu menuFacturaInst;
    private javax.swing.JMenu menuFacturaServ;
    private javax.swing.JMenu menuLectura;
    private javax.swing.JMenu menuParametro;
    // End of variables declaration//GEN-END:variables
}
