
import clases.conexión;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author David
 */
public class interfazConsultaFactServ extends javax.swing.JDialog {

    /**
     * Creates new form interfazConsultaServPorCed
     */
    public interfazConsultaFactServ(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    public void cargarTabla2(ArrayList datos) {

        String[] titulos = (String[]) datos.get(0);
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);

        for (int i = 1; i < datos.size(); i++) {
            String registro[] = (String[]) datos.get(i);
            modelo.addRow(registro);
        }
        tablaFacturas.setModel(modelo);  //Nombre de la tabla    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngreso = new javax.swing.JLabel();
        campoIngreso = new javax.swing.JTextField();
        opcionConsulta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFacturas = new javax.swing.JTable();
        btnConsultar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Factura Servicio");

        lblIngreso.setText("Numero:");

        campoIngreso.setColumns(13);

        opcionConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CODIGO MEDIDOR" }));
        opcionConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionConsultaActionPerformed(evt);
            }
        });

        tablaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaFacturas);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIngreso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(opcionConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngreso)
                    .addComponent(campoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcionConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionConsultaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int opcion = opcionConsulta.getSelectedIndex();
        conexión prueba = new conexión();
        if (opcion == 0) {//Codigo de medidor
            //CONSULTA

            try {
                try {
                    prueba.conectar();

                    /*CONSULTA
                    System.out.println("select FACTURA_SERVICIO.NUM_FAC_SERV as \"Numero Factura\",FACTURA_SERVICIO.FECHA_PAGO from FACTURA_SERVICIO,LEC_FACT_PAGADA " +
"where FACTURA_SERVICIO.NUM_FAC_SERV = LEC_FACT_PAGADA.NUM_FAC_SERV " +
"and LEC_FACT_PAGADA.COD_MEDIDOR ="+"'"+campoIngreso.getText()+"'");*/
                    ArrayList a = prueba.impresion("select FACTURA_SERVICIO.NUM_FAC_SERV as \"Numero Factura\",FACTURA_SERVICIO.FECHA_PAGO from FACTURA_SERVICIO,LEC_FACT_PAGADA "
                            + "where FACTURA_SERVICIO.NUM_FAC_SERV = LEC_FACT_PAGADA.NUM_FAC_SERV "
                            + "and LEC_FACT_PAGADA.COD_MEDIDOR =" + "'" + campoIngreso.getText() + "'");

                    cargarTabla2(a);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(conexión.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException sqlExepcion) {
                System.out.println(sqlExepcion);
            }
        } else if (opcion == 1) {
            try {
                try {
                    prueba.conectar();
                    ArrayList a = prueba.impresion("select LEC_FACT_PAGADA.NUM_FAC_SERV FROM LEC_FACT_PAGADA WHERE LEC_FACT_PAGADA.NUM_FAC_SERV=" + campoIngreso.getText());
                    if(a.size() >1){
                        //consultarFactura consFacServ = new consultarFactura((JFrame) getContentPane().getParent(),true);
                        //consFacServ.setVisible(true);
                    }else{
                 
                        JOptionPane.showMessageDialog(null,"No existe dicha factura!");
                        campoIngreso.setText("");
                        campoIngreso.requestFocus();
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(conexión.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException sqlExepcion) {
                System.out.println(sqlExepcion);
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazConsultaFactServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazConsultaFactServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazConsultaFactServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazConsultaFactServ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                interfazConsultaFactServ dialog = new interfazConsultaFactServ(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JTextField campoIngreso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JComboBox<String> opcionConsulta;
    private javax.swing.JTable tablaFacturas;
    // End of variables declaration//GEN-END:variables
}
